# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ChooseFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qgis.gui import QgsFileWidget

class Ui_chooseFile(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 97)
        self.mQgsFileWidget = QgsFileWidget(Dialog)
        self.mQgsFileWidget.setGeometry(QtCore.QRect(10, 30, 381, 27))
        self.mQgsFileWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Netherlands))
        self.mQgsFileWidget.setObjectName("mQgsFileWidget")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 351, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(270, 60, 93, 28))
        self.pushButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Netherlands))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.mQgsFileWidget.setAccessibleName(_translate("Dialog", "FileWidget"))
        self.mQgsFileWidget.setAccessibleDescription(_translate("Dialog", "Pick a location to save your new vector layer"))
        self.label.setText(_translate("Dialog", "Choose location new vector layer"))
        self.pushButton.setText(_translate("Dialog", "Generate layer"))

